<a href="https://colab.research.google.com/github/diogopelinson/AIFeedbackHub/blob/main/Redes_Neurais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import torch

lista = [[1,2,3],
        [4,5,6]]

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [13]:
import numpy as np

arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)

print(arr)
print(arr.dtype)

print(tns.dtype)
print(tns)

[[0.11934482 0.40430408 0.74187717 0.35270426]
 [0.08755336 0.96764199 0.20311547 0.67737902]
 [0.86078275 0.0805387  0.94835684 0.03450954]]
float64
torch.float64
tensor([[0.1193, 0.4043, 0.7419, 0.3527],
        [0.0876, 0.9676, 0.2031, 0.6774],
        [0.8608, 0.0805, 0.9484, 0.0345]], dtype=torch.float64)


In [14]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3)

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 1.6706, -1.6680, -0.1902],
        [ 0.3531,  1.7238,  1.9088],
        [ 0.9329, -0.1592, -1.0574]])


In [15]:
arr = tnsr.data.numpy()
print(arr)
print(type(arr))

[[ 1.6705683  -1.6679574  -0.19015618]
 [ 0.3531459   1.7238492   1.9087982 ]
 [ 0.9328834  -0.15923043 -1.0573714 ]]
<class 'numpy.ndarray'>


In [16]:
print(tnsr)
tnsr[0,2] = -10

print("")
print(tnsr)
print("")
print(tnsr[:,2])

print(tnsr[0,2])

tensor([[ 1.6706, -1.6680, -0.1902],
        [ 0.3531,  1.7238,  1.9088],
        [ 0.9329, -0.1592, -1.0574]])

tensor([[  1.6706,  -1.6680, -10.0000],
        [  0.3531,   1.7238,   1.9088],
        [  0.9329,  -0.1592,  -1.0574]])

tensor([-10.0000,   1.9088,  -1.0574])
tensor(-10.)


In [17]:
#Operacoes com tensores
#Tudo feito ponto a ponto
#Ele multiplica de ponto a ponto e nao a multiplicacao de matrizes que esperamos
tns = tnsr[0:2, :]
print(tns)
print(tns1)
print("")
print(tns+tns1)
print("")
print(tns*tns1)
print("")
print(tns1/tns)
print("")
print(tns1//tns)
print("")
print(tns1%tns)
print("")

#Funcoes para fazer produto interno
print(torch.mm(tns1, tns.T))


tensor([[  1.6706,  -1.6680, -10.0000],
        [  0.3531,   1.7238,   1.9088]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[ 2.6706, -0.6680, -9.0000],
        [ 1.3531,  2.7238,  2.9088]])

tensor([[  1.6706,  -1.6680, -10.0000],
        [  0.3531,   1.7238,   1.9088]])

tensor([[ 0.5986, -0.5995, -0.1000],
        [ 2.8317,  0.5801,  0.5239]])

tensor([[ 0., -1., -1.],
        [ 2.,  0.,  0.]])

tensor([[ 1.0000, -0.6680, -9.0000],
        [ 0.2937,  1.0000,  1.0000]])

tensor([[-9.9974,  3.9858],
        [-9.9974,  3.9858]])


In [18]:
#Tamanho de um Tensor
tns = torch.randn(2,2,3)
print(tns)

print("")
print(tns.size())

print("")
#Achatar tensor
tns = tns.view(tns.size(0), -1) #O mais comum eh isso, manter a primeira dimensao e achatar o resto
#Poderia ser 12
#Ou -1 que tambem seria achatar

print(tns)
print(tns.size())



tensor([[[ 0.8213, -2.0432, -0.2242],
         [ 1.3123, -1.4611, -0.9145]],

        [[ 1.0257,  1.7737, -0.9813],
         [ 0.2194, -0.1086, -1.2480]]])

torch.Size([2, 2, 3])

tensor([[ 0.8213, -2.0432, -0.2242,  1.3123, -1.4611, -0.9145],
        [ 1.0257,  1.7737, -0.9813,  0.2194, -0.1086, -1.2480]])
torch.Size([2, 6])


In [21]:
tns = torch.randn(9, 12)
tns1 = tns[0:5, 0:4]
tns2 = tns[5:, 4:]

resultado = torch.mm(tns1, tns2)
print(resultado.size())

torch.Size([5, 8])


In [27]:
tns1 = torch.randn(7,7,3)
tns2 = torch.randn(147, 1)

tns1 = tns1.view(-1, 1)
soma = tns1 + tns2
print(soma)

tensor([[ 2.1934],
        [ 3.0286],
        [-1.2769],
        [ 0.0637],
        [-0.9403],
        [ 3.8798],
        [-0.6736],
        [ 0.0415],
        [-1.1295],
        [ 0.0107],
        [-0.9947],
        [-0.3236],
        [ 2.2188],
        [-0.3862],
        [ 1.8888],
        [-0.2455],
        [ 1.6536],
        [-1.0512],
        [-0.2758],
        [-0.0644],
        [ 2.5495],
        [ 1.1179],
        [ 0.9566],
        [ 1.5159],
        [-1.2174],
        [-1.3743],
        [ 0.2546],
        [ 1.3130],
        [ 0.5265],
        [-3.6912],
        [-0.9546],
        [ 1.8558],
        [ 1.5512],
        [ 1.1550],
        [ 0.1549],
        [ 0.4250],
        [-0.3205],
        [-0.3333],
        [-1.1497],
        [-0.1624],
        [-0.2870],
        [-2.5962],
        [-0.0466],
        [-0.4057],
        [-0.6142],
        [ 1.2243],
        [-1.1065],
        [-0.7395],
        [-1.8646],
        [ 1.5259],
        [-0.1754],
        [ 1.4829],
        [ 0.

In [20]:
#GPU Cast
#Serve para pegar dados e colocar na GPU
#Para um processamento mais rapido
#Verificar se a GPU esta disponivel

tns = torch.randn(10)

if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
print(device)

tns = tns.to(device)
print(tns)

cuda
tensor([-0.4773,  0.5175, -0.4780,  1.5565,  0.3729,  1.8591, -0.3137, -0.8350,
        -0.2895, -1.1840], device='cuda:0')
